-- Performance indexes
CREATE INDEX idx_profiles_role ON profiles(role);
CREATE INDEX idx_profiles_email ON profiles(email);
CREATE INDEX idx_teachers_profile_id ON teachers(profile_id);
CREATE INDEX idx_supervisors_profile_id ON supervisors(profile_id);
CREATE INDEX idx_parents_profile_id ON parents(profile_id);
CREATE INDEX idx_students_class_section ON students(class_id, section_id);
CREATE INDEX idx_parent_students_parent ON parent_students(parent_id);
CREATE INDEX idx_parent_students_student ON parent_students(student_id);
CREATE INDEX idx_teacher_classes_teacher ON teacher_classes(teacher_id);
CREATE INDEX idx_teacher_classes_class ON teacher_classes(class_id);
CREATE INDEX idx_supervisor_teachers_supervisor ON supervisor_teachers(supervisor_id);
CREATE INDEX idx_attendance_class_date ON attendance(class_id, section_id, date);
CREATE INDEX idx_attendance_records_attendance ON attendance_records(attendance_id);
CREATE INDEX idx_attendance_records_student ON attendance_records(student_id);
CREATE INDEX idx_homework_teacher ON homework(teacher_id);
CREATE INDEX idx_homework_class ON homework(class_id, section_id);
CREATE INDEX idx_homework_due_date ON homework(due_date);
CREATE INDEX idx_homework_submissions_homework ON homework_submissions(homework_id);
CREATE INDEX idx_homework_submissions_student ON homework_submissions(student_id);
CREATE INDEX idx_exams_teacher ON exams(teacher_id);
CREATE INDEX idx_exams_class ON exams(class_id, section_id);
CREATE INDEX idx_results_exam ON results(exam_id);
CREATE INDEX idx_results_student ON results(student_id);
CREATE INDEX idx_tasks_assigned_to ON tasks(assigned_to);
CREATE INDEX idx_tasks_status ON tasks(status);
CREATE INDEX idx_tasks_due_date ON tasks(due_date);
CREATE INDEX idx_tasks_escalation_level ON tasks(escalation_level);
CREATE INDEX idx_feedback_from ON feedback(from_user);
CREATE INDEX idx_feedback_to ON feedback(to_user);
CREATE INDEX idx_feedback_status ON feedback(status);
CREATE INDEX idx_escalations_task ON escalations(task_id);
CREATE INDEX idx_escalations_feedback ON escalations(feedback_id);
CREATE INDEX idx_notifications_user ON notifications(user_id);
CREATE INDEX idx_notifications_read ON notifications(is_read);
CREATE INDEX idx_audit_logs_user ON audit_logs(user_id);
CREATE INDEX idx_audit_logs_table ON audit_logs(table_name);
CREATE INDEX idx_audit_logs_created ON audit_logs(created_at);
CREATE INDEX idx_calendar_events_class ON calendar_events(class_id);
CREATE INDEX idx_calendar_events_dates ON calendar_events(start_date, end_date);
CREATE INDEX idx_system_settings_key ON system_settings(key);
